spring:
  application:
    name: ticker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ticker_db?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

server:
  servlet:
    session:
      timeout: 30m
    encoding:
      force: true
      charset: UTF-8
      enabled: true

