spring:
  application:
    name: ticker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ticker_db?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  firebase:
    config-path: ticker-d92f7-firebase-adminsdk-fbsvc-7b468ffbee.json
  redis:
    host: localhost
    port: 6379
server:
  servlet:
    session:
      timeout: 30m
