name: Java & Gradle CI

on:
  push:
    branches:
      - '**'
    paths:
      - '**.java'
      - '**.yml'
      - '**.properties'
      - 'build.gradle'
      - 'settings.gradle'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Create Firebase config file
        run: echo "${{ secrets.FIREBASE_JSON_CONTENT }}" > src/main/resources/ticker-d92f7-firebase-adminsdk-fbsvc-7b468ffbee.json

      - name: Set Firebase config path
        run: echo "FIREBASE_CONFIG_PATH=src/main/resources/ticker-d92f7-firebase-adminsdk-fbsvc-7b468ffbee.json" >> $GITHUB_ENV

      - name: Test with Gradle
        run: ./gradlew clean test
        env:
          SPRING_PROFILES_ACTIVE: test